"use strict";

const C = {
	USER_ROLE_ADMIN: "admin", 
	USER_ROLE_PM: "project_manager", 
	USER_ROLE_EMPLOYEE: "employee",

	TASK_STATUS_BACKLOG: "backlog",
	TASK_STATUS_WIP: "wip",
	TASK_STATUS_REVIEW: "review",
	TASK_STATUS_DONE: "done",

	TOKEN_TYPE_VERIFICATION: "verification",
	TOKEN_TYPE_PASSWORDLESS: "passwordless",
	TOKEN_TYPE_PASSWORD_RESET: "password-reset",
	TOKEN_TYPE_API_KEY: "api-key"
};

module.exports = {
	...C,

	USER_ROLES: [
		C.USER_ROLE_ADMIN,
		C.USER_ROLE_PM,
		C.USER_ROLE_EMPLOYEE
	],

	TOKEN_TYPES: [
		C.TOKEN_TYPE_VERIFICATION,
		C.TOKEN_TYPE_PASSWORDLESS,
		C.TOKEN_TYPE_PASSWORD_RESET,
		C.TOKEN_TYPE_API_KEY
	],

	TASK_STATUSES: [
		C.TASK_STATUS_BACKLOG,
		C.TASK_STATUS_WIP,
		C.TASK_STATUS_REVIEW,
		C.TASK_STATUS_DONE
	],
};