version: "3.3"

services:
  api:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 5000
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=5000"
    networks:
      - internal

  user:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: user
    depends_on:
      - nats
    networks:
      - internal

  organisations:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: organisations
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  projects:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: projects
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  projectsReplica:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: projects
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  tasks:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: tasks
    depends_on:
      - mongo
      - nats
    networks:
      - internal
  
  tasksReplica:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: tasks
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  tasksAttachments:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: tasks.attachments
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  tasksAttachmentsReplica:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: tasks.attachments
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  tasksComments:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: tasks.comments
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  tokens:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: tokens
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  mail:
    build:
      context: .
    image: formo-backend
    env_file: docker-compose.env
    environment:
      SERVICES: mail
    depends_on:
      - mongo
      - nats
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal

  nats:
    image: nats:2
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 5000:80
      - 5001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
